### ISSUE TITLE
Flashcards

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/flashcard_service#2]
## Description
Parent issue.
Implement basic flashcards that can be added to a course/chapter.
Answer is shown and not checked automatically but manually by yourself.
Results can be sent to the progress (service?).

## Sub-issues / Children

- [ ] Flashcards frontend implementation concept [wiki49](https://github.com/orgs/IT-REX-Platform/projects/1/views/1?pane=issue&itemId=30373678)
- [ ] Flashcards frontend [gits-frontend37](https://github.com/orgs/IT-REX-Platform/projects/1/views/1?pane=issue&itemId=30373006)
- [x] Flashcards backend #3 
- [x] Flashcards schema [wiki43](https://github.com/orgs/IT-REX-Platform/projects/1/views/1?pane=issue&itemId=30373023)
